<?php
/** @var $block \Js\CustomOrderAttributes\Block\Adminhtml\Order\Create\Form\SellerCode */
$parentOrder = $block->getParentOrderForReorder();
?>

<div class="admin__page-section-title <?= $block->escapeHtmlAttr($block->getHeaderCssClass()) ?>">
    <span class="title"><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    <div class="actions"></div>
</div>
<div class="admin__field">
    <label for="seller_code" class="admin__field-label"><span><?= __('Seller Code') ?></span></label>
    <div class="admin__field-control">
        <input class="admin__control-text" type="text" name="seller_code" id="seller_code" value="<?= $parentOrder;?>"/>
    </div>
</div>
